name: Format

on: workflow_dispatch

jobs:
  formatting:
    name: Java formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --skip-reflowing-long-strings --skip-javadoc-formatting"
          version: v1.16.0
      - name: Print diffs
        run: git --no-pager diff --exit-code