name: GraalVM CE tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dotnet test targets
        working-directory: ./language/src/test/resources/TypeParsingTestTargets
        run: dotnet build --configuration Release

      - name: Build with Maven
        run: mvn package
